import {globeStyle} from './map-style.js';
const $ = id => document.getElementById(id);
const params = new URLSearchParams(location.search);
let data, map, groups = new Map(), filtered = [], selected = '', pageSize = 80, spinning = !matchMedia('(prefers-reduced-motion: reduce)').matches;
let dates=[], request=0, last=0, entityId=params.get('entity')||'', markerGroups=[], bright=true, revision=0;
const state={category:params.get('category')||'',q:params.get('q')||'',from:params.get('from')||'',to:params.get('to')||''};
const stop=()=>{spinning=false;};
function safeURL(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function logo(e){const el=document.createElement('span');el.className='logo';el.textContent=e.name.slice(0,1).toUpperCase();if(Number.isInteger(e.sprite)&&data.meta.sprite){const {cols,size,url}=data.meta.sprite;el.textContent='';el.classList.add('sprite');el.style.backgroundImage=`url(${JSON.stringify(url)})`;el.style.backgroundSize=`${cols*36}px auto`;el.style.backgroundPosition=`${-(e.sprite%cols)*36}px ${-Math.floor(e.sprite/cols)*36}px`;el.dataset.sprite=e.sprite;el.dataset.cols=cols;}return el;}
function urlState(){const p=new URLSearchParams();for(const [k,v] of Object.entries(state))if(v)p.set(k,v);if(selected)p.set('point',selected);if(entityId)p.set('entity',entityId);const c=map.getCenter();p.set('lng',c.lng.toFixed(3));p.set('lat',c.lat.toFixed(3));p.set('zoom',map.getZoom().toFixed(2));p.set('pitch',map.getPitch().toFixed(1));p.set('bearing',map.getBearing().toFixed(1));history.replaceState(null,'',`${location.pathname}?${p}`);}
function matches(e){return(!state.category||e.category===state.category)&&(!state.q||`${e.name} ${e.city} ${e.country}`.toLowerCase().includes(state.q.toLowerCase()))&&(!state.from||e.date&&e.date>=state.from)&&(!state.to||e.date&&e.date<=state.to);}
function aggregate(){
 filtered=data.entities.filter(matches);groups=new Map();
 for(const e of filtered){let g=groups.get(e.group);if(!g){g={id:e.group,label:e.label,entities:[],weight:0,x:0,y:0,z:0,coordinates:[e.lng,e.lat]};groups.set(e.group,g);}g.entities.push(e);g.weight+=e.weight;const la=e.lat*Math.PI/180,lo=e.lng*Math.PI/180;g.x+=Math.cos(la)*Math.cos(lo);g.y+=Math.cos(la)*Math.sin(lo);g.z+=Math.sin(la);}
 return {type:'FeatureCollection',features:[...groups.values()].map(g=>{if(data.meta.grouping==='grid')g.coordinates=[Math.atan2(g.y,g.x)*180/Math.PI,Math.atan2(g.z,Math.hypot(g.x,g.y))*180/Math.PI];if(data.meta.grouping==='grid')g.label=`Nearby locations · ${g.coordinates[1].toFixed(1)}°, ${g.coordinates[0].toFixed(1)}°`;return {type:'Feature',properties:{id:g.id,weight:g.weight,count:g.entities.length},geometry:{type:'Point',coordinates:g.coordinates}};})};
}
function update(){revision++;const fc=aggregate();map.getSource('locations').setData(fc);markerGroups=[...groups.values()].sort((a,b)=>b.entities.length-a.entities.length).slice(0,18);renderOverview();renderSearch();$('status').textContent=`${filtered.length.toLocaleString()} entities · ${groups.size.toLocaleString()} locations · ${filtered.reduce((s,e)=>s+e.weight,0).toLocaleString()} weight`;$('hover').hidden=true;if(selected){if(groups.has(selected))renderDetail();else closeDetail();}urlState();}
function closeDetail(){selected='';entityId='';$('detail').hidden=true;document.body.classList.remove('has-detail');$('cluster').replaceChildren();$('hover').hidden=true;urlState();}
function renderDetail(){const g=groups.get(selected);if(!g)return;$('detail').hidden=false;document.body.classList.add('has-detail');$('back').hidden=!entityId;$('entity-info').hidden=true;$('entities').hidden=false;$('grouping').textContent=data.meta.grouping==='grid'?'GROUPED BY SPATIAL CELL':data.meta.grouping==='city'?'GROUPED BY CITY':'EXACT COORDINATE GROUP';$('detail-title').textContent=g.label;$('detail-count').textContent=`${g.entities.length.toLocaleString()} entities · ${g.weight.toLocaleString()} weight`;$('entities').replaceChildren();for(const e of g.entities.slice(0,pageSize)){const row=document.createElement('article'),body=document.createElement('div'),title=document.createElement('strong'),sub=document.createElement('small');title.textContent=e.name;sub.textContent=`${e.category} · ${e.city||e.country||'Location'}${e.date?' · '+e.date:''} · ${e.weight.toLocaleString()}`;body.append(title,sub);if(e.url&&safeURL(e.url)){const a=document.createElement('a');a.href=safeURL(e.url);a.target='_blank';a.rel='noopener noreferrer';a.textContent='Source ↗';body.append(a);}row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label',`Explore ${e.name}`);row.onclick=event=>{if(event.target.closest('a'))return;openEntity(e);};row.onkeydown=event=>{if(event.key==='Enter')openEntity(e);};row.append(logo(e),body);$('entities').append(row);}$('more').hidden=pageSize>=g.entities.length;renderCluster();if(entityId){const e=g.entities.find(e=>String(e.id)===entityId);if(e)openEntity(e,false);else entityId='';}}
function focus(id,fly=true){const g=groups.get(id);if(!g)return;stop();selected=id;entityId='';pageSize=80;$('hover').hidden=true;renderDetail();if(fly){$('loading').hidden=false;const mobile=innerWidth<=720;map.flyTo({center:g.coordinates,zoom:data.meta.grouping==='grid'?7.5:10.4,pitch:42,duration:1500,padding:mobile?{top:60,bottom:280,left:20,right:20}:{top:70,bottom:70,left:280,right:340}});map.once('moveend',()=>{if(selected===id){renderDetail();map.once('idle',()=>{$('loading').hidden=true;});}urlState();});}else renderDetail();urlState();}
function hover(g,e){if(!g)return;const el=$('hover');el.replaceChildren();const strong=document.createElement('strong');strong.textContent=g.label;const p=document.createElement('p');p.textContent=`${g.entities.length.toLocaleString()} entities · ${g.weight.toLocaleString()} weight`;const preview=document.createElement('div');preview.className='preview';for(const item of g.entities.slice(0,5))preview.append(logo(item));el.append(strong,p,preview);el.hidden=false;el.style.left=`${Math.max(8,Math.min(innerWidth-275,e.point.x+15))}px`;el.style.top=`${Math.max(8,Math.min(innerHeight-180,e.point.y+15))}px`;}
function timeline(){dates=[...new Set(data.entities.map(e=>e.date).filter(Boolean))].sort();if(!dates.length)return;$('time').hidden=false;document.body.classList.add('has-dates');for(const id of ['from','to'])$(id).max=dates.length-1;$('from').value=Math.max(0,dates.indexOf(state.from));$('to').value=state.to?Math.max(0,dates.indexOf(state.to)):dates.length-1;const histogram=new Array(40).fill(0);for(const e of data.entities)if(e.date)histogram[Math.min(39,Math.floor(dates.indexOf(e.date)/dates.length*40))]++;const max=Math.max(...histogram,1);$('histogram').innerHTML=histogram.map((v,i)=>`<rect x="${i*6}" y="${36-v/max*36}" width="4" height="${v/max*36}" fill="#cfaa77"/>`).join('');const labels=()=>{$('from-label').value=dates[+$('from').value];$('to-label').value=dates[+$('to').value];};labels();for(const id of ['from','to'])$(id).oninput=()=>{stop();if(+$('from').value>+$('to').value)$(id==='from'?'to':'from').value=$(id).value;state.from=dates[+$('from').value];state.to=dates[+$('to').value];labels();update();};}
async function main(){
 const r=await fetch('data.json');if(!r.ok)throw Error(`Dataset HTTP ${r.status}`);data=await r.json();if(!Array.isArray(data.entities)||!data.entities.length)throw Error('Dataset has no entities');document.title=data.meta.title;$('title').textContent=data.meta.title;$('source').textContent=data.meta.source;$('notice').textContent=`${data.meta.unplaced||0} unplaced · ${data.meta.excluded||0} excluded · ${data.meta.grouping==='grid'?'Spatial bins show nearby entities, not a city or street address.':'Coordinates are source anchors.'}`;
 for(const c of [...new Set(data.entities.map(e=>e.category))].sort()){const o=document.createElement('option');o.value=c;o.textContent=c;$('category').append(o);}$('category').value=state.category;$('search').value=state.q;timeline();
 const n=(key,def,min,max)=>{const v=Number(params.get(key));return params.has(key)&&Number.isFinite(v)&&v>=min&&v<=max?v:def;};
 map=new maplibregl.Map({container:'map',style:globeStyle("bright"),center:[n('lng',-28,-180,180),n('lat',30,-85,85)],zoom:n('zoom',innerWidth<760?1.1:1.95,0,18),pitch:n('pitch',0,0,60),bearing:n('bearing',0,-180,180),renderWorldCopies:false,attributionControl:true});
 map.addControl(new maplibregl.NavigationControl(),'bottom-right');map.on('error',e=>{console.error('Map error:',e.error);$('notice').textContent='Map tiles could not load. Check network access and reload.';});
 const el=map.getContainer();el.addEventListener('pointerdown',stop);el.addEventListener('wheel',stop,{passive:true});document.querySelectorAll('button,input,select').forEach(el=>{el.addEventListener('pointerdown',stop);el.addEventListener('keydown',stop);});
 map.on('load',()=>{map.setSky({'sky-color':'#0a0a0a','horizon-color':'#3a1606','fog-color':'#0a0a0a','atmosphere-blend':['interpolate',['linear'],['zoom'],0,0.85,4,0.35,7,0]});map.addSource('locations',{type:'geojson',data:aggregate()});map.addLayer({id:'point-glow',type:'circle',source:'locations',paint:{'circle-radius':['interpolate',['linear'],['sqrt',['get','count']],1,8,10,30,100,65],'circle-color':'#f94f00','circle-opacity':0.22,'circle-blur':1}});map.addLayer({id:'points',type:'circle',source:'locations',paint:{'circle-radius':['interpolate',['linear'],['sqrt',['get','count']],0,1.5,3,2,15,4,100,9],'circle-color':'#f94f00','circle-stroke-width':0.3,'circle-stroke-color':'#ffb27a','circle-opacity':0.8}});map.addLayer({id:'point-hit',type:'circle',source:'locations',layout:{'circle-sort-key':['get','weight']},paint:{'circle-radius':12,'circle-opacity':0}});map.on('mousemove','point-hit',e=>{map.getCanvas().style.cursor='pointer';if(!selected)hover(groups.get(e.features[0].properties.id),e);});map.on('mouseleave','point-hit',()=>{map.getCanvas().style.cursor='';$('hover').hidden=true;});map.on('click','point-hit',e=>focus(e.features[0].properties.id));update();if(params.get('point')){const savedEntity=entityId;focus(params.get('point'),false);entityId=savedEntity;renderDetail();}window.__dataGlobe={map,get groups(){return [...groups.values()].map(g=>({id:g.id,coordinates:g.coordinates,count:g.entities.length,weight:g.weight}));},get filteredCount(){return filtered.length;},get spinning(){return spinning;},get selected(){return selected;},ready:true};
 const tick=t=>{const dt=Math.min(50,t-last||0);last=t;if(spinning&&!map.isEasing()&&!document.hidden)map.setCenter([map.getCenter().lng-dt*0.0025,map.getCenter().lat]);request=requestAnimationFrame(tick);};request=requestAnimationFrame(tick);});
 map.on('render',placeOverlays);map.on('moveend',()=>{if(!spinning)urlState();renderWall();});$('category').addEventListener('change',()=>{stop();state.category=$('category').value;update();});let timer;$('search').addEventListener('input',()=>{stop();clearTimeout(timer);timer=setTimeout(()=>{state.q=$('search').value.trim();update();},150);});$('close').onclick=closeDetail;$('back').onclick=()=>{entityId='';renderDetail();urlState();};$('toggle-filters').onclick=()=>{const expanded=$('controls').classList.toggle('expanded');$('toggle-filters').setAttribute('aria-expanded',expanded);$('toggle-filters').textContent=expanded?'Filters −':'Filters +';};$('theme').onclick=()=>{bright=!bright;const palette=globeStyle(bright?'bright':'dark');for(const layer of palette.layers)for(const [key,value] of Object.entries(layer.paint||{}))map.setPaintProperty(layer.id,key,value);$('theme').textContent=bright?'Dark land':'Light land';};document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(entityId){entityId='';renderDetail();urlState();}else closeDetail();}});$('more').onclick=()=>{pageSize+=80;renderDetail();};$('reset').onclick=()=>{stop();state.category=state.q=state.from=state.to='';$('category').value=$('search').value='';closeDetail();timeline();update();map.flyTo({center:[-28,30],zoom:innerWidth<760?1.1:1.95,pitch:0,bearing:0,padding:{top:0,bottom:0,left:0,right:0},duration:1200});};$('share').onclick=async()=>{urlState();try{await navigator.clipboard.writeText(location.href);$('notice').textContent='Link copied';}catch{$('notice').textContent='Copy the URL from the address bar to share this view.';}};
 window.addEventListener('popstate',()=>{const p=new URLSearchParams(location.search);for(const key of Object.keys(state))state[key]=p.get(key)||'';$('category').value=state.category;$('search').value=state.q;selected=p.get('point')||'';entityId=p.get('entity')||'';timeline();update();if(selected)renderDetail();else closeDetail();const lng=Number(p.get('lng')),lat=Number(p.get('lat')),zoom=Number(p.get('zoom'));if(p.has('lng')&&Number.isFinite(lng)&&Math.abs(lng)<=180&&Number.isFinite(lat)&&Math.abs(lat)<=85&&Number.isFinite(zoom)&&zoom>=0&&zoom<=18)map.jumpTo({center:[lng,lat],zoom});});window.addEventListener('pagehide',()=>{cancelAnimationFrame(request);map.remove();});
}
main().catch(e=>{console.error(e);$('status').textContent=`Could not load globe: ${e.message}`;});
function openEntity(e,fly=true){
 stop();entityId=String(e.id);$('back').hidden=false;$('entity-info').hidden=false;$('entities').hidden=true;$('more').hidden=true;$('detail-title').textContent=e.name;$('detail-count').textContent=[e.category,e.city,e.country].filter(Boolean).join(' · ');
 const info=$('entity-info');info.replaceChildren(logo(e));for(const [label,value] of [['Latitude',e.lat],['Longitude',e.lng],['Weight',e.weight],['Source date',e.date]]){if(value===undefined||value===null||value==='')continue;const line=document.createElement('p');line.textContent=`${label}: ${value}`;info.append(line);}if(safeURL(e.url)){const link=document.createElement('a');link.href=safeURL(e.url);link.target='_blank';link.rel='noopener noreferrer';link.textContent='Explore the source ↗';info.append(link);}
 if(fly)map.flyTo({center:[e.lng,e.lat],zoom:10.4,pitch:42,duration:1200,padding:innerWidth<760?{top:230,bottom:350,left:15,right:15}:{top:60,bottom:60,left:320,right:380}});urlState();
}
function entityButton(e){const b=document.createElement('button');b.type='button';b.title=e.name;b.setAttribute('aria-label',e.name);b.append(logo(e));b.onclick=()=>{focus(e.group,false);openEntity(e);};return b;}
function renderOverview(){
 const ranking=$('ranking');ranking.replaceChildren();const top=[...groups.values()].sort((a,b)=>b.entities.length-a.entities.length).slice(0,5);for(const g of top){const b=document.createElement('button');b.className='rank';const line=document.createElement('span'),name=document.createElement('b'),count=document.createElement('small'),bar=document.createElement('i');name.textContent=g.label;count.textContent=g.entities.length.toLocaleString();line.append(name,count);bar.style.width=`${Math.max(6,100*g.entities.length/top[0].entities.length)}%`;b.append(line,bar);b.onclick=()=>focus(g.id);ranking.append(b);}
 $('chips').replaceChildren();const counts=new Map();for(const e of data.entities)counts.set(e.category,(counts.get(e.category)||0)+1);for(const [category,count] of counts){const b=document.createElement('button');b.textContent=category.replaceAll('_',' ');b.setAttribute('aria-pressed',state.category===category);const small=document.createElement('small');small.textContent=count.toLocaleString();b.append(small);b.onclick=()=>{stop();state.category=state.category===category?'':category;$('category').value=state.category;update();};$('chips').append(b);}
 renderWall();
}
function renderSearch(){const results=$('results');results.replaceChildren();results.hidden=!state.q;for(const e of filtered.slice(0,8)){const b=entityButton(e);const text=document.createElement('span');text.textContent=e.name;b.append(text);results.append(b);}}
function renderWall(){if(!map||!data)return;const bounds=map.getBounds(),visible=filtered.filter(e=>bounds.contains([e.lng,e.lat]));$('wall').replaceChildren(...visible.slice(0,24).map(entityButton));$('view-count').textContent=visible.length.toLocaleString();}
function renderCluster(){const el=$('cluster');el.replaceChildren();const g=groups.get(selected);if(!g)return;const disc=document.createElement('div');disc.className='cluster-disc';el.append(disc);const note=document.createElement('div');note.className='cluster-note';note.textContent=data.meta.grouping==='grid'?'Grouped nearby · select for exact coordinates':data.meta.grouping==='city'?'Grouped by city · logos are not street addresses':'Source coordinate · select an entity';el.append(note);g.entities.slice(0,24).forEach((e,i)=>{const b=entityButton(e);b.className='cluster-item';const ring=Math.floor(i/8)+1,angle=(i%8)*Math.PI/4;b.dataset.x=Math.cos(angle)*ring*(innerWidth<760?31:40);b.dataset.y=Math.sin(angle)*ring*(innerWidth<760?29:37);el.append(b);});placeOverlays();}
function placeOverlays(){
 if(!map||!data)return;for(const el of document.querySelectorAll('.sprite')){const size=el.clientWidth,cols=Number(el.dataset.cols),index=Number(el.dataset.sprite);el.style.backgroundSize=`${cols*size}px auto`;el.style.backgroundPosition=`${-(index%cols)*size}px ${-Math.floor(index/cols)*size}px`;}const zoom=map.getZoom(),rim=$('rim'),bloom=$('bloom');rim.hidden=bloom.hidden=zoom>3.5;const pad=map.getPadding(),cx=pad.left+(innerWidth-pad.left-pad.right)/2,cy=pad.top+(innerHeight-pad.top-pad.bottom)/2;
 if(zoom<3.5){const onGlobe=x=>{try{const q=map.project(map.unproject([x,cy]));return Math.hypot(q.x-x,q.y-cy)<1.5;}catch{return false;}};let lo=10,hi=Math.max(innerWidth,innerHeight);while(hi-lo>1){const mid=(lo+hi)/2;if(onGlobe(cx+mid))lo=mid;else hi=mid;}for(const [el,r] of [[rim,lo/0.905],[bloom,lo*1.6]])Object.assign(el.style,{left:`${cx-r}px`,top:`${cy-r}px`,width:`${r*2}px`,height:`${r*2}px`});}
 const marker=$('markers');if(!marker.childElementCount||marker.dataset.version!==String(revision)){marker.replaceChildren();marker.dataset.version=String(revision);for(const g of markerGroups){const b=document.createElement('button');b.className='city-chip';b.dataset.group=g.id;b.append(logo(g.entities[0]));const name=document.createElement('b');name.textContent=g.label;const count=document.createElement('span');count.textContent=g.entities.length.toLocaleString();b.append(name,count);b.onclick=()=>focus(g.id);marker.append(b);}}
 // Keep overlays on the visible hemisphere; cap them independently of dataset size.
 const boxes=[],ctr=map.getCenter(),la0=ctr.lat*Math.PI/180;for(const b of marker.children){const g=groups.get(b.dataset.group);if(!g){b.hidden=true;continue;}const p=map.project(g.coordinates),la=g.coordinates[1]*Math.PI/180,dl=(g.coordinates[0]-ctr.lng)*Math.PI/180,cosAng=Math.sin(la0)*Math.sin(la)+Math.cos(la0)*Math.cos(la)*Math.cos(dl);b.hidden=!!selected||zoom>5||cosAng<0.42||boxes.length>=7||boxes.some(q=>Math.abs(q.x-p.x)<220&&Math.abs(q.y-p.y)<40)||p.x<320&&innerWidth>=760||p.x>innerWidth-300&&innerWidth>=760||p.y<260&&innerWidth<760;if(!b.hidden)boxes.push(p);b.style.transform=`translate(${p.x+9}px,${p.y-15}px)`;}
 const g=groups.get(selected);if(!g)return;const p=map.project(g.coordinates);for(const child of $('cluster').children){child.style.left=`${p.x+(Number(child.dataset.x)||0)}px`;child.style.top=`${p.y+(Number(child.dataset.y)||0)-(child.classList.contains('cluster-note')?(innerWidth<760?135:170):0)}px`;}
}
