#!/usr/bin/env python3
"""Create a minimal Promptfoo config for current versus candidate evaluation."""
from __future__ import annotations

import argparse
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--current", required=True)
    parser.add_argument("--candidate", required=True)
    parser.add_argument("--provider", default="openai:gpt-5-mini")
    parser.add_argument("--out", default="promptfooconfig.yaml")
    args = parser.parse_args()
    out_path = Path(args.out).resolve()
    prompt_dir = out_path.parent / (out_path.stem + "-prompts")
    prompt_dir.mkdir(parents=True, exist_ok=True)
    prompt_paths = []
    for label, source_name in (("current", args.current), ("candidate", args.candidate)):
        source = Path(source_name).resolve()
        rendered = prompt_dir / f"{label}.txt"
        rendered.write_text(
            source.read_text(encoding="utf-8") + "\n\nUser task:\n{{question}}\n",
            encoding="utf-8",
        )
        prompt_paths.append(rendered)
    config = f'''# Generated by Edge System Prompt Doctor. Add representative tests before running.
providers:
  - {args.provider}
prompts:
  - file://{prompt_paths[0]}
  - file://{prompt_paths[1]}

tests:
  # Replace with 8 to 20 representative cases. Keep final holdout separate.
  - vars:
      question: "Example task, replace me"
    assert:
      - type: llm-rubric
        value: "The output follows the target agent contract and completes the task correctly."
'''
    out_path.write_text(config, encoding="utf-8")
    print(out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
