#!/usr/bin/env python3
"""Strip C2PA and AI-generation metadata from PNG/JPEG/WebP images and sidecars."""

import sys
import json
import struct
import argparse
import os
import re
import stat
import tempfile
import zlib
import xml.etree.ElementTree as ET
from pathlib import Path
from datetime import datetime

PNG_SIG = b'\x89PNG\r\n\x1a\n'
JPEG_SOI = b'\xFF\xD8'
WEBP_SIG = b'RIFF'

# Scanned against raw binary (whole segments, chunk payloads, JPEG trailers and
# the final output file). Keep every entry long and distinctive enough that it
# does not collide with compressed pixel data.
AI_KEYWORDS = [b'c2pa', b'openai', b'chatgpt', b'gpt-image', b'trainedalgorithmicmedia',
               b'org.contentauth', b'contentcredentials', b'trufo', b'midjourney',
               b'stable diffusion', b'stable-diffusion', b'stablediffusion',
               b'stability.ai', b'firefly', b'imagen', b'grok', b'adobe stock',
               b'automatic1111', b'comfyui', b'invokeai', b'novelai', b'ideogram',
               b'dall-e', b'leonardo.ai', b'runwayml', b'craiyon']

# Scanned against fields that are known to be human-readable text (EXIF ASCII
# values, XMP element text, JSON sidecar strings, PNG text chunks). False
# positives here cost one metadata field, not a corrupted file, so this list can
# afford to be looser than AI_KEYWORDS.
AI_TEXT_MARKERS = [k.decode() for k in AI_KEYWORDS] + [
    'dalle', 'sora', 'nano banana', 'gemini', 'bing image creator',
    'designer.microsoft', 'playground v2', 'recraft', 'krea.ai', 'flux.1',
    'sdxl', 'sd-webui', 'a1111', 'generated by ai', 'ai-generated',
    'ai generated', 'made with ai', 'generative ai', 'algorithmicmedia',
    'digitalsourcetype', 'content credentials', 'contentauthenticity',
]

C2PA_JUMBF_UUID = bytes.fromhex('6332706100110010800000aa00389b71')
JPEG_XMP_HEADERS = (
    b'http://ns.adobe.com/xap/1.0/\x00',
    b'http://ns.adobe.com/xmp/extension/\x00',
)

# EXIF/TIFF tags that carry attribution rather than rendering information.
# Orientation, dimensions, colour and thumbnail tags are deliberately absent.
EXIF_ATTRIBUTION_TAGS = {
    0x010D: 'DocumentName',
    0x010E: 'ImageDescription',
    0x010F: 'Make',
    0x0110: 'Model',
    0x0131: 'Software',
    0x013B: 'Artist',
    0x8298: 'Copyright',
    0x9286: 'UserComment',
    0x9C9B: 'XPTitle',
    0x9C9C: 'XPComment',
    0x9C9D: 'XPAuthor',
    0x9C9E: 'XPKeywords',
    0x9C9F: 'XPSubject',
    0xA430: 'CameraOwnerName',
    0xA433: 'LensMake',
    0xA434: 'LensModel',
}
EXIF_SUBIFD_TAGS = (0x8769, 0xA005, 0x8825)
TIFF_TYPE_SIZES = {1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 6: 1, 7: 1, 8: 2, 9: 4, 10: 8,
                   11: 4, 12: 8, 13: 4, 16: 8, 17: 8, 18: 8}

# PNG text keywords that exist only to record how a generator made the image.
# Matched on the keyword itself, so an Automatic1111 "parameters" chunk goes
# even when its body happens to name no known tool.
PNG_GENERATOR_TEXT_KEYS = {
    'parameters', 'prompt', 'negative_prompt', 'workflow', 'extra_pnginfo',
    'sd-metadata', 'sd_metadata', 'dream', 'generation_data', 'aigc',
    'ai_metadata', 'c2pa', 'contentcredentials', 'provenance',
}

# JSON sidecar keys with the same property.
JSON_GENERATOR_KEYS = {
    'parameters', 'prompt', 'negative_prompt', 'workflow', 'extra_pnginfo',
    'sd-metadata', 'sd_metadata', 'sd_model', 'sd_model_hash', 'generation_data',
    'c2pa', 'content_credentials', 'contentcredentials', 'provenance', 'aigc',
    'ai_metadata', 'generator', 'digitalsourcetype', 'creatortool',
}

SIDECAR_SUFFIXES = ('.xmp', '.json')
XMP_AI_NAME_HINTS = ('c2pa', 'contentauth', 'contentcredential')


def _binary_markers(blob: bytes):
    low = blob.lower()
    return [k.decode() for k in AI_KEYWORDS if k in low]


def _text_has_marker(text: str) -> bool:
    if not text:
        return False
    low = text.lower()
    return any(m in low for m in AI_TEXT_MARKERS)


# --------------------------------------------------------------------------
# EXIF / TIFF
# --------------------------------------------------------------------------

def scrub_tiff(block: bytearray):
    """Erase AI attribution tag values inside a TIFF block, in place.

    The value bytes are overwritten with zeros so nothing survives for `strings`
    to find, and the entry is left as a valid empty value. Nothing is moved, so
    every other offset in the block stays correct and orientation, colour and
    thumbnail data are untouched. Returns the names of the tags that were hit.
    """
    hits = []
    if len(block) < 8:
        return hits
    if block[:2] == b'II':
        endian = '<'
    elif block[:2] == b'MM':
        endian = '>'
    else:
        return hits
    if struct.unpack(endian + 'H', block[2:4])[0] != 42:
        return hits

    queue = [struct.unpack(endian + 'I', block[4:8])[0]]
    seen = set()
    while queue:
        ifd = queue.pop(0)
        if ifd in seen or ifd < 8 or ifd + 2 > len(block):
            continue
        seen.add(ifd)
        count = struct.unpack(endian + 'H', block[ifd:ifd + 2])[0]
        entries_end = ifd + 2 + count * 12
        if entries_end > len(block):
            continue
        for i in range(count):
            entry = ifd + 2 + i * 12
            tag, typ = struct.unpack(endian + 'HH', block[entry:entry + 4])
            n = struct.unpack(endian + 'I', block[entry + 4:entry + 8])[0]
            size = TIFF_TYPE_SIZES.get(typ, 0) * n
            if tag in EXIF_SUBIFD_TAGS and typ == 4 and n == 1:
                queue.append(struct.unpack(endian + 'I', block[entry + 8:entry + 12])[0])
                continue
            if tag not in EXIF_ATTRIBUTION_TAGS or size == 0:
                continue
            if size <= 4:
                value_at, value_len = entry + 8, size
            else:
                value_at = struct.unpack(endian + 'I', block[entry + 8:entry + 12])[0]
                value_len = size
                if value_at < 8 or value_at + value_len > len(block):
                    continue
            raw = bytes(block[value_at:value_at + value_len])
            text = raw.decode('utf-8', errors='ignore')
            if tag in (0x9C9B, 0x9C9C, 0x9C9D, 0x9C9E, 0x9C9F):
                text = raw.decode('utf-16-le', errors='ignore')
            if not _text_has_marker(text):
                continue
            for j in range(value_at, value_at + value_len):
                block[j] = 0
            # Leave a valid, empty one-byte value that points nowhere.
            struct.pack_into(endian + 'I', block, entry + 4, 1)
            struct.pack_into(endian + 'I', block, entry + 8, 0)
            hits.append(EXIF_ATTRIBUTION_TAGS[tag])
        if entries_end + 4 <= len(block):
            queue.append(struct.unpack(endian + 'I', block[entries_end:entries_end + 4])[0])
    return hits


def _scrub_exif_payload(payload: bytes):
    """Scrub a payload that is a TIFF block, optionally behind an Exif\\0\\0 header."""
    offset = 6 if payload.startswith(b'Exif\x00\x00') else 0
    block = bytearray(payload[offset:])
    hits = scrub_tiff(block)
    if not hits:
        return payload, []
    return payload[:offset] + bytes(block), hits


def _is_structured_exif(payload: bytes) -> bool:
    """Recognize an EXIF/TIFF payload whose orientation and thumbnails matter."""
    if not payload.startswith(b'Exif\x00\x00') or len(payload) < 14:
        return False
    tiff = payload[6:]
    if tiff[:2] == b'II':
        return tiff[2:4] == b'\x2a\x00'
    if tiff[:2] == b'MM':
        return tiff[2:4] == b'\x00\x2a'
    return False


# --------------------------------------------------------------------------
# PNG
# --------------------------------------------------------------------------

def _png_text_fields(chunk_type: bytes, body: bytes):
    """Return (keyword, decoded text) for a PNG text chunk, decompressing zTXt."""
    nul = body.find(b'\x00')
    if nul == -1:
        return '', body.decode('utf-8', errors='ignore')
    keyword = body[:nul].decode('latin-1', errors='ignore')
    rest = body[nul + 1:]
    try:
        if chunk_type == b'tEXt':
            text = rest.decode('latin-1', errors='ignore')
        elif chunk_type == b'zTXt':
            text = zlib.decompress(rest[1:]).decode('utf-8', errors='ignore')
        else:  # iTXt: flag, method, language\0, translated\0, text
            compressed = rest[0] if rest else 0
            tail = rest[2:]
            for _ in range(2):
                cut = tail.find(b'\x00')
                if cut == -1:
                    return keyword, ''
                tail = tail[cut + 1:]
            text = (zlib.decompress(tail) if compressed else tail).decode('utf-8', errors='ignore')
    except (zlib.error, IndexError):
        # Undecodable payload: fall back to the raw bytes so a keyword sitting
        # in there uncompressed is still caught.
        text = rest.decode('latin-1', errors='ignore')
    return keyword, text


def _png_chunk(chunk_type: bytes, body: bytes) -> bytes:
    return (struct.pack('>I', len(body)) + chunk_type + body
            + struct.pack('>I', zlib.crc32(chunk_type + body) & 0xFFFFFFFF))


def strip_png(data: bytes):
    if not data.startswith(PNG_SIG):
        raise ValueError("Not a valid PNG")
    out = bytearray(PNG_SIG)
    idx = 8
    removed = []
    while idx < len(data):
        if idx + 8 > len(data):
            out.extend(data[idx:])
            break
        length = struct.unpack('>I', data[idx:idx+4])[0]
        chunk_type = data[idx+4:idx+8]
        end = idx + 8 + length + 4
        if end > len(data):
            out.extend(data[idx:])
            break
        body = data[idx+8:idx+8+length]
        if chunk_type == b'caBX':
            removed.append(f"caBX ({length} bytes)")
            idx = end
            continue
        # Only textual metadata is eligible for keyword-based removal. Removing
        # an entire eXIf chunk can also remove orientation and thumbnails, so
        # eXIf is scrubbed tag by tag below instead.
        if chunk_type in (b'tEXt', b'iTXt', b'zTXt'):
            keyword, text = _png_text_fields(chunk_type, body)
            if keyword.strip().lower() in PNG_GENERATOR_TEXT_KEYS:
                removed.append(f"{chunk_type.decode()}:{keyword} ({length} bytes)")
                idx = end
                continue
            if _text_has_marker(text) or _text_has_marker(keyword):
                removed.append(f"{chunk_type.decode()}:{keyword or '?'} ({length} bytes)")
                idx = end
                continue
        if chunk_type == b'eXIf':
            scrubbed, hits = _scrub_exif_payload(body)
            if hits:
                removed.append(f"eXIf attribution tags ({', '.join(hits)})")
                out.extend(_png_chunk(chunk_type, scrubbed))
                idx = end
                continue
        out.extend(data[idx:end])
        idx = end
    return bytes(out), removed


# --------------------------------------------------------------------------
# JPEG
# --------------------------------------------------------------------------

def _jpeg_segment(data: bytes, idx: int):
    """Return (marker, end, payload) for a length-bearing marker at idx."""
    if idx + 4 > len(data) or data[idx] != 0xFF:
        return None
    marker = data[idx + 1]
    if marker in (0x00, 0x01, 0xD8, 0xD9) or 0xD0 <= marker <= 0xD7:
        return None
    length = struct.unpack('>H', data[idx + 2:idx + 4])[0]
    end = idx + 2 + length
    if length < 2 or end > len(data):
        return None
    return marker, end, data[idx + 4:end]


def _jpeg_app11_group(data: bytes, idx: int):
    """Return the contiguous JPEG-XT APP11 group beginning at idx, if any."""
    first = _jpeg_segment(data, idx)
    if first is None or first[0] != 0xEB or len(first[2]) < 8 or first[2][:2] != b'JP':
        return None
    instance = first[2][2:4]
    expected_sequence = struct.unpack('>I', first[2][4:8])[0]
    if expected_sequence != 1:
        return None

    end = idx
    box_data = bytearray()
    count = 0
    while True:
        segment = _jpeg_segment(data, end)
        if segment is None or segment[0] != 0xEB:
            break
        payload = segment[2]
        if len(payload) < 8 or payload[:2] != b'JP' or payload[2:4] != instance:
            break
        sequence = struct.unpack('>I', payload[4:8])[0]
        if sequence != expected_sequence:
            break
        box_data.extend(payload[8:])
        end = segment[1]
        count += 1
        expected_sequence += 1

    is_c2pa = _is_c2pa_jumbf(box_data)
    return end, count, is_c2pa


def _box_at(data: bytes, idx: int, limit: int):
    """Parse one ISO BMFF/JUMBF box without accepting truncated lengths."""
    if idx + 8 > limit:
        return None
    size = struct.unpack('>I', data[idx:idx + 4])[0]
    box_type = data[idx + 4:idx + 8]
    header_size = 8
    if size == 1:
        if idx + 16 > limit:
            return None
        size = struct.unpack('>Q', data[idx + 8:idx + 16])[0]
        header_size = 16
    elif size == 0:
        size = limit - idx
    end = idx + size
    if size < header_size or end > limit:
        return None
    return box_type, idx + header_size, end


def _is_c2pa_jumbf(data: bytes) -> bool:
    """Match the C2PA manifest-store UUID and label in its JUMBF description."""
    outer = _box_at(data, 0, len(data))
    if outer is None or outer[0] != b'jumb':
        return False
    description = _box_at(data, outer[1], outer[2])
    if description is None or description[0] != b'jumd':
        return False
    payload = data[description[1]:description[2]]
    if len(payload) < 17 or payload[:16] != C2PA_JUMBF_UUID:
        return False
    toggles = payload[16]
    if not toggles & 0x02:
        return False
    label_end = payload.find(b'\x00', 17)
    return label_end != -1 and payload[17:label_end] == b'c2pa'


def _clean_jpeg_trailer(trailer: bytes, depth: int):
    """Clean the bytes that follow EOI.

    They are outside the codestream, so no decoder shows them, but a C2PA
    manifest parked there is still read by the platforms this skill exists to
    defeat. An appended image (MPO/MPF) carries pixels, so it is cleaned
    recursively rather than dropped. Anything else that still smells of AI
    provenance after box-level surgery is dropped whole and reported.
    """
    if not trailer:
        return b'', []
    if trailer.startswith(JPEG_SOI) and depth < 4:
        try:
            cleaned, removed = strip_jpeg(trailer, depth + 1)
            return cleaned, [f"appended image: {r}" for r in removed]
        except ValueError:
            pass

    out = bytearray()
    removed = []
    pos = 0
    while pos < len(trailer):
        box = _box_at(trailer, pos, len(trailer))
        if box is None:
            break
        end = box[2]
        chunk = trailer[pos:end]
        if _is_c2pa_jumbf(chunk):
            removed.append(f"post-EOI C2PA manifest ({end - pos} bytes)")
        else:
            markers = _binary_markers(chunk)
            if markers:
                removed.append(
                    f"post-EOI data ({end - pos} bytes, {', '.join(markers)})")
            else:
                out.extend(chunk)
        pos = end

    rest = trailer[pos:]
    if rest:
        markers = _binary_markers(rest)
        if markers:
            removed.append(f"post-EOI trailer ({len(rest)} bytes, {', '.join(markers)})")
        else:
            out.extend(rest)
    return bytes(out), removed


def strip_jpeg(data: bytes, _depth: int = 0):
    if not data.startswith(JPEG_SOI):
        raise ValueError("Not a valid JPEG")
    out = bytearray(JPEG_SOI)
    idx = 2
    removed = []
    in_scan = False
    marker_from_scan = False
    while idx < len(data):
        if in_scan:
            marker_start = data.find(b'\xFF', idx)
            if marker_start == -1:
                out.extend(data[idx:])
                break
            out.extend(data[idx:marker_start])
            marker_code = marker_start
            while marker_code < len(data) and data[marker_code] == 0xFF:
                marker_code += 1
            if marker_code == len(data):
                out.extend(data[marker_start:])
                break
            marker = data[marker_code]
            if marker == 0x00 or 0xD0 <= marker <= 0xD7:
                out.extend(data[marker_start:marker_code + 1])
                idx = marker_code + 1
                continue
            # Any leading 0xFF bytes are fill; the final one prefixes the marker.
            out.extend(data[marker_start:marker_code - 1])
            idx = marker_code - 1
            in_scan = False
            marker_from_scan = True

        # Preserve malformed/out-of-place bytes rather than silently dropping
        # them. This is also the safety net for incomplete JPEGs without EOI.
        if data[idx] != 0xFF:
            out.append(data[idx])
            idx += 1
            continue
        if idx + 1 >= len(data):
            out.extend(data[idx:])
            idx = len(data)
            break
        marker = data[idx+1]
        # 0xFF fill, stuffed 0xFF00, SOI, restart markers, TEM: no length field.
        if marker == 0xFF:
            out.append(data[idx])
            idx += 1
            continue
        if marker in (0x00, 0x01, 0xD8) or 0xD0 <= marker <= 0xD7:
            out.extend(data[idx:idx+2])
            idx += 2
            marker_from_scan = False
            continue
        if marker == 0xD9:
            out.extend(data[idx:idx+2])
            idx += 2
            trailer, trailer_removed = _clean_jpeg_trailer(data[idx:], _depth)
            out.extend(trailer)
            removed.extend(trailer_removed)
            break

        app11_group = _jpeg_app11_group(data, idx) if marker == 0xEB else None
        if app11_group is not None:
            group_end, count, is_c2pa = app11_group
            if is_c2pa:
                removed.append(f"APP11/C2PA ({count} segment{'s' if count != 1 else ''})")
                idx = group_end
                marker_from_scan = False
                continue

        segment = _jpeg_segment(data, idx)
        if segment is None:
            out.extend(data[idx:])
            break
        marker, end, payload = segment
        # XMP APP1 records go whole. Structured EXIF keeps orientation and
        # thumbnails but loses its attribution tags. APP13/APP14 affect
        # presentation and are never keyword-stripped.
        is_xmp = payload.startswith(JPEG_XMP_HEADERS)
        structured_exif = _is_structured_exif(payload)
        is_unstructured_ai_exif = payload.startswith(b'Exif\x00\x00') and not structured_exif
        if marker == 0xE1 and (is_xmp or is_unstructured_ai_exif):
            text = payload.decode('utf-8', errors='ignore')
            if _text_has_marker(text):
                removed.append(f"APP1/AI ({len(payload)} bytes)")
                idx = end
                marker_from_scan = False
                continue
        if marker == 0xE1 and structured_exif:
            scrubbed, hits = _scrub_exif_payload(payload)
            if hits:
                removed.append(f"APP1/EXIF attribution tags ({', '.join(hits)})")
                out.extend(data[idx:idx + 4])
                out.extend(scrubbed)
                idx = end
                marker_from_scan = False
                continue
        out.extend(data[idx:end])
        idx = end
        if marker == 0xDA:
            in_scan = True
        elif marker == 0xDC and marker_from_scan:
            # DNL may interrupt entropy-coded data without ending the scan.
            in_scan = True
        marker_from_scan = False
    return bytes(out), removed


# --------------------------------------------------------------------------
# WebP
# --------------------------------------------------------------------------

def strip_webp(data: bytes):
    if not data.startswith(WEBP_SIG) or len(data) < 12 or data[8:12] != b'WEBP':
        raise ValueError("Not a valid WebP")
    declared_size = struct.unpack('<I', data[4:8])[0]
    riff_end = 8 + declared_size
    if declared_size < 4 or riff_end > len(data):
        raise ValueError("Truncated WebP RIFF container")
    out = bytearray(data[:12])
    idx = 12
    removed = []
    vp8x_flags_offset = None
    removed_xmp = False
    kept_xmp = False
    while idx < riff_end:
        if idx + 8 > riff_end:
            raise ValueError("Truncated WebP chunk header")
        fourcc = data[idx:idx+4]
        size = struct.unpack('<I', data[idx+4:idx+8])[0]
        pad = 1 if size % 2 else 0
        end = idx + 8 + size + pad
        if end > riff_end:
            raise ValueError("Truncated WebP chunk payload")
        name = fourcc.decode('ascii', errors='replace')
        body = data[idx+8:idx+8+size]
        remove = fourcc == b'C2PA'
        if fourcc == b'XMP ' and _text_has_marker(body.decode('utf-8', errors='ignore')):
            remove = True
            removed_xmp = True
        elif fourcc == b'XMP ':
            kept_xmp = True
        if remove:
            removed.append(f"{name} ({size} bytes)")
            idx = end
            continue
        if fourcc == b'VP8X' and size >= 1:
            vp8x_flags_offset = len(out) + 8
        if fourcc == b'EXIF':
            scrubbed, hits = _scrub_exif_payload(body)
            if hits:
                removed.append(f"EXIF attribution tags ({', '.join(hits)})")
                out.extend(data[idx:idx+8])
                out.extend(scrubbed)
                out.extend(data[idx+8+size:end])
                idx = end
                continue
        out.extend(data[idx:end])
        idx = end
    if removed_xmp and not kept_xmp and vp8x_flags_offset is not None:
        out[vp8x_flags_offset] &= ~0x04
    struct.pack_into('<I', out, 4, len(out) - 8)
    out.extend(data[riff_end:])
    return bytes(out), removed


# --------------------------------------------------------------------------
# Sidecars
# --------------------------------------------------------------------------

def find_sidecars(image_path: Path):
    """Locate .xmp/.json sidecars next to an image, both naming conventions."""
    found = []
    seen = set()
    try:
        image_id = image_path.stat()
        seen.add((image_id.st_dev, image_id.st_ino))
    except OSError:
        pass
    for suffix in SIDECAR_SUFFIXES:
        for variant in (suffix, suffix.upper()):
            for candidate in (image_path.with_name(image_path.name + variant),
                              image_path.with_name(image_path.stem + variant)):
                if not candidate.is_file():
                    continue
                # Identify by inode: on a case-insensitive filesystem the .xmp
                # and .XMP spellings are the same file.
                info = candidate.stat()
                key = (info.st_dev, info.st_ino)
                if key in seen:
                    continue
                seen.add(key)
                found.append(candidate)
    return found


def sidecar_output_name(sidecar: Path, image_in: Path, image_out: Path) -> Path:
    """Map a sidecar onto the cleaned image's name so the pair stays together."""
    if sidecar.name.lower().startswith(image_in.name.lower()):
        return image_out.with_name(image_out.name + sidecar.suffix.lower())
    return image_out.with_name(image_out.stem + sidecar.suffix.lower())


def _qname(tag: str, prefixes: dict) -> str:
    if tag.startswith('{'):
        uri, local = tag[1:].split('}', 1)
        return f"{prefixes.get(uri, uri)}:{local}"
    return tag


def _split_tag(tag: str):
    if tag.startswith('{'):
        uri, local = tag[1:].split('}', 1)
        return uri, local
    return '', tag


def _xmp_name_is_ai(uri: str, local: str) -> bool:
    blob = f"{uri} {local}".lower()
    return any(hint in blob for hint in XMP_AI_NAME_HINTS)


RDF_NS = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'


def _scrub_xmp_element(elem, removed, prefixes, is_root=False, context=''):
    """Drop AI provenance from an XMP tree. Returns True if elem must be removed.

    `context` names the closest enclosing property so a hit inside an rdf:Alt
    is reported as dc:description/rdf:li rather than a bare rdf:li.
    """
    uri, local = _split_tag(elem.tag)
    label = _qname(elem.tag, prefixes)
    reported = f"{context}/{label}" if context else label
    if not is_root and _xmp_name_is_ai(uri, local):
        removed.append(reported)
        return True

    before = len(removed)
    for key, value in list(elem.attrib.items()):
        key_uri, key_local = _split_tag(key)
        if _xmp_name_is_ai(key_uri, key_local) or _text_has_marker(value):
            del elem.attrib[key]
            removed.append(f"{reported}/@{_qname(key, prefixes)}")

    child_context = context if (is_root or uri == RDF_NS) else label
    had_children = len(elem) > 0
    for child in list(elem):
        if _scrub_xmp_element(child, removed, prefixes, context=child_context):
            elem.remove(child)

    if not is_root and _text_has_marker(elem.text or ''):
        removed.append(reported)
        return True
    # A property element that lost all of its content is now noise: drop it too,
    # but only when it was this pass that emptied it.
    if (not is_root and had_children and len(elem) == 0
            and not (elem.text or '').strip() and len(removed) > before):
        return True
    return False


def strip_xmp_text(text: str):
    """Return (cleaned_xmp, removed_property_names). Raises on unparseable XML."""
    prefixes = {uri: prefix for prefix, uri
                in re.findall(r'xmlns:([A-Za-z_][\w.\-]*)\s*=\s*"([^"]*)"', text)}
    for uri, prefix in prefixes.items():
        try:
            ET.register_namespace(prefix, uri)
        except ValueError:
            pass

    match = re.search(r'<(?!\?|!)([A-Za-z_][\w.\-:]*)', text)
    if not match:
        raise ValueError("no XML element found")
    root_name = match.group(1)
    closing = f"</{root_name}>"
    close_at = text.rfind(closing)
    if close_at == -1:
        raise ValueError(f"unterminated <{root_name}> element")
    head = text[:match.start()]
    body = text[match.start():close_at + len(closing)]
    tail = text[close_at + len(closing):]

    root = ET.fromstring(body)
    removed = []
    _scrub_xmp_element(root, removed, prefixes, is_root=True)
    if not removed:
        return text, []
    return head + ET.tostring(root, encoding='unicode') + tail, removed


def _scrub_json(node, removed, path=''):
    """Return the cleaned node. Records the dotted path of everything dropped."""
    if isinstance(node, dict):
        cleaned = {}
        for key, value in node.items():
            here = f"{path}.{key}" if path else str(key)
            if str(key).strip().lower() in JSON_GENERATOR_KEYS or _text_has_marker(str(key)):
                removed.append(here)
                continue
            if isinstance(value, str) and _text_has_marker(value):
                removed.append(here)
                continue
            cleaned[key] = _scrub_json(value, removed, here)
        return cleaned
    if isinstance(node, list):
        cleaned = []
        for i, value in enumerate(node):
            here = f"{path}[{i}]"
            if isinstance(value, str) and _text_has_marker(value):
                removed.append(here)
                continue
            cleaned.append(_scrub_json(value, removed, here))
        return cleaned
    return node


def strip_json_text(text: str):
    """Return (cleaned_json_text, removed_paths). Raises on unparseable JSON."""
    parsed = json.loads(text)
    removed = []
    cleaned = _scrub_json(parsed, removed)
    if not removed:
        return text, []
    return json.dumps(cleaned, indent=2, ensure_ascii=False) + '\n', removed


def clean_sidecar_bytes(path: Path, raw: bytes):
    """Return (cleaned_bytes, removed, error). error is set when raw is unparseable."""
    try:
        text = raw.decode('utf-8')
    except UnicodeDecodeError:
        text = raw.decode('utf-8', errors='replace')
    suffix = path.suffix.lower()
    try:
        if suffix == '.json':
            cleaned, removed = strip_json_text(text)
        else:
            cleaned, removed = strip_xmp_text(text)
    except Exception as exc:
        markers = _binary_markers(raw)
        return None, [], f"{type(exc).__name__}: {exc}" + (
            f" (file still contains {', '.join(markers)})" if markers else "")
    return cleaned.encode('utf-8'), removed, None


# --------------------------------------------------------------------------
# Output plumbing
# --------------------------------------------------------------------------

def neutral_name(path: Path) -> Path:
    """Generate a camera-style neutral filename in the same directory."""
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    candidate = path.parent / f"IMG_{ts}{path.suffix.lower()}"
    n = 1
    while candidate.exists():
        candidate = path.parent / f"IMG_{ts}_{n}{path.suffix.lower()}"
        n += 1
    return candidate


def verify_pixels(original: bytes, cleaned: bytes) -> str | None:
    """Confirm the strip did not touch a single pixel. Returns an error or None."""
    try:
        from PIL import Image, ImageSequence
    except ImportError:
        return "pixel verification unavailable: Pillow is not installed"
    import io
    import hashlib
    try:
        a = Image.open(io.BytesIO(original))
        a.verify()
        a = Image.open(io.BytesIO(original))
    except Exception as exc:
        return f"original file does not decode as an image: {exc}"
    try:
        b = Image.open(io.BytesIO(cleaned))
        b.verify()
        b = Image.open(io.BytesIO(cleaned))
        if getattr(a, 'n_frames', 1) != getattr(b, 'n_frames', 1):
            return (f"frame count changed: {getattr(a, 'n_frames', 1)} -> "
                    f"{getattr(b, 'n_frames', 1)}")
        for frame_index, (af, bf) in enumerate(zip(ImageSequence.Iterator(a),
                                                   ImageSequence.Iterator(b))):
            if af.size != bf.size:
                return f"frame {frame_index} dimensions changed: {af.size} -> {bf.size}"
            ha = hashlib.sha256(af.convert('RGBA').tobytes()).digest()
            hb = hashlib.sha256(bf.convert('RGBA').tobytes()).digest()
            if ha != hb:
                return f"frame {frame_index} pixel data changed"
    except Exception as exc:
        return f"cleaned file no longer decodes as an image: {exc}"
    return None


def _same_file_state(before, after) -> bool:
    return (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns) == (
        after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns)


def _atomic_replace(path: Path, data: bytes, expected_state):
    """Durably replace path while keeping the old file until the new one is safe."""
    current = path.stat()
    if not _same_file_state(expected_state, current):
        raise RuntimeError("input changed while it was being processed")

    fd, temp_name = tempfile.mkstemp(prefix=f'.{path.name}.', dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, 'wb') as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
            os.fchmod(handle.fileno(), stat.S_IMODE(current.st_mode))
            try:
                os.fchown(handle.fileno(), current.st_uid, current.st_gid)
            except PermissionError:
                pass
        if temp_path.read_bytes() != data:
            raise OSError("temporary-file verification failed")
        os.replace(temp_path, path)
        try:
            directory_fd = os.open(path.parent, os.O_RDONLY | getattr(os, 'O_DIRECTORY', 0))
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
        except OSError:
            # The complete file has already been atomically installed. Directory
            # fsync is unavailable on some filesystems and platforms.
            pass
    finally:
        if temp_path.exists():
            temp_path.unlink()


def _atomic_output(path: Path, data: bytes, fallback_mode: int = 0o600):
    """Write an explicit output without ever truncating an existing file."""
    existing_mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else fallback_mode
    fd, temp_name = tempfile.mkstemp(prefix=f'.{path.name}.', dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, 'wb') as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
            os.fchmod(handle.fileno(), existing_mode)
        if temp_path.read_bytes() != data:
            raise OSError("temporary-file verification failed")
        os.replace(temp_path, path)
    finally:
        if temp_path.exists():
            temp_path.unlink()


# --------------------------------------------------------------------------
# Drivers
# --------------------------------------------------------------------------

def process_sidecar_file(path: Path, output: Path | None, in_place: bool) -> bool:
    """Clean a sidecar given directly on the command line."""
    raw = path.read_bytes()
    cleaned, removed, error = clean_sidecar_bytes(path, raw)
    if error:
        print(f"FAILED {path}: sidecar could not be parsed: {error}")
        print("  Nothing was written. Inspect or delete this file by hand before publishing.")
        return False
    if not removed:
        print(f"No AI/C2PA metadata found in {path}")
        return True
    out_path = output or (path if in_place else neutral_name(path))
    if output and not out_path.parent.is_dir():
        print(f"Error: output directory does not exist: {out_path.parent}")
        return False
    _atomic_output(out_path, cleaned, stat.S_IMODE(path.stat().st_mode))
    print(f"Cleaned {path} -> {out_path}")
    for item in removed:
        print(f"  Removed: {item}")
    return _report_residue(out_path)


def _report_residue(out_path: Path) -> bool:
    """Scan a written file for leftovers. A leftover is a failure, not a note."""
    remaining = _binary_markers(out_path.read_bytes())
    if not remaining:
        return True
    print(f"  FAILED: {out_path} still contains {remaining}")
    print("  Do not publish this file. Inspect it with `exiftool -a -G1 -u` "
          "and `strings` before use.")
    return False


def process(path: Path, output: Path | None = None, in_place: bool = False) -> bool:
    if path.suffix.lower() in SIDECAR_SUFFIXES:
        return process_sidecar_file(path, output, in_place)

    source_path = path.resolve(strict=True)
    source_state = source_path.stat()
    data = source_path.read_bytes()
    if not _same_file_state(source_state, source_path.stat()):
        print(f"ABORTED {path}: input changed while it was being read")
        return False
    if data.startswith(PNG_SIG):
        cleaned, removed = strip_png(data)
    elif data.startswith(JPEG_SOI):
        cleaned, removed = strip_jpeg(data)
    elif data.startswith(WEBP_SIG):
        cleaned, removed = strip_webp(data)
    else:
        print(f"Unsupported format: {path}")
        return False

    # A clean image next to a sidecar that still names the generator is not a
    # clean result, so sidecars are resolved before anything is reported.
    sidecars = find_sidecars(path)
    sidecar_plans = []
    sidecar_failed = False
    for sidecar in sidecars:
        raw = sidecar.read_bytes()
        sc_clean, sc_removed, sc_error = clean_sidecar_bytes(sidecar, raw)
        if sc_error:
            sidecar_failed = True
            sidecar_plans.append((sidecar, None, [], sc_error))
        else:
            sidecar_plans.append((sidecar, sc_clean, sc_removed, None))

    sidecar_changes = any(p[2] for p in sidecar_plans)
    if not removed and not sidecar_changes and not sidecar_failed:
        suffix = f" (and {len(sidecars)} sidecar file(s))" if sidecars else ""
        print(f"No AI/C2PA metadata found in {path}{suffix}")
        return True

    if removed:
        # Refuse to write anything that is not byte-identical in pixels. Without
        # this an in-place run can destroy the user's only copy of a photo.
        damage = verify_pixels(data, cleaned)
        if damage:
            print(f"ABORTED {path}: {damage}")
            print("  Original left untouched. This is a bug, please report it.")
            return False

    if output:
        out_path = output
    elif in_place:
        out_path = path
    else:
        out_path = neutral_name(path)

    if output and not out_path.parent.is_dir():
        print(f"Error: output directory does not exist: {out_path.parent}")
        return False

    replacing_source = in_place
    if output:
        replacing_source = output.resolve() == source_path

    if replacing_source:
        if removed:
            _atomic_replace(source_path, cleaned, source_state)
        out_path = path
    elif output:
        _atomic_output(out_path, cleaned, stat.S_IMODE(source_state.st_mode))
    else:
        out_path.write_bytes(cleaned)

    if removed:
        print(f"Cleaned {path} -> {out_path}")
        for r in removed:
            print(f"  Removed: {r}")
        print("  Pixels: unchanged (verified)")
    elif replacing_source:
        print(f"{path}: image itself was already clean, sidecars below")
    else:
        print(f"Copied {path} -> {out_path} (image itself was already clean)")

    ok = _report_residue(out_path)

    for sidecar, sc_clean, sc_removed, sc_error in sidecar_plans:
        if sc_error:
            print(f"  FAILED sidecar {sidecar}: could not be parsed: {sc_error}")
            print("  It was left untouched. Inspect or delete it before publishing.")
            ok = False
            continue
        if not sc_removed:
            print(f"  Sidecar {sidecar.name}: checked, no AI metadata")
            continue
        sc_out = sidecar if replacing_source else sidecar_output_name(sidecar, path, out_path)
        _atomic_output(sc_out, sc_clean, stat.S_IMODE(sidecar.stat().st_mode))
        print(f"  Cleaned sidecar {sidecar} -> {sc_out}")
        for item in sc_removed:
            print(f"    Removed: {item}")
        ok = _report_residue(sc_out) and ok
    return ok


def main():
    parser = argparse.ArgumentParser(
        description="Strip C2PA/AI metadata from images and their .xmp/.json sidecars")
    parser.add_argument("paths", nargs="+", help="Image or sidecar file(s) to clean")
    destination = parser.add_mutually_exclusive_group()
    destination.add_argument("-o", "--output", help="Explicit output path (single input only)")
    destination.add_argument("-i", "--in-place", action="store_true",
                             help="Overwrite the original file instead of renaming")
    args = parser.parse_args()

    if args.output and len(args.paths) > 1:
        print("Error: -o/--output can only be used with a single input file")
        sys.exit(1)

    failed = False
    for p in args.paths:
        path = Path(p)
        if not path.is_file():
            print(f"No such file: {p}")
            sys.exit(1)
        if not process(path, Path(args.output) if args.output else None, args.in_place):
            failed = True
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
